# hide service clients with the following names
clients_by_name:
  - '/moveit_component_spawner/destroy_object'
  - '/moveit_component_spawner/spawn_object'
  - '/apply_planning_scene'
  - '/get_planning_scene'
  - '/assembly_scene_publisher/destroy_object'
  - '/assembly_scene_publisher/spawn_object'
  - '/unpause_physics'
  - '/spawn_entity'
  - '/set_planner_params'
  - '/save_map'
  - '/rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic/get_interactive_markers'
  - '/reset_world'
  - '/reset_simulation'
  - '/query_planner_interface'
  - '/plan_kinematic_path'
  - '/pause_physics'
  - '/load_map'
  - '/get_planner_params'
  - '/get_model_list'
  - '/delete_entity'
  - '/compute_ik'
  - '/compute_fk'
  - '/compute_cartesian_path'
  - '/check_if_robot_model_exists_in_warehouse'
  - '/clear_octomap'
  - '/clear_link_wrenches'
  - '/clear_joint_efforts'
  - '/check_state_validity'
  - '/apply_link_wrench'
  - '/apply_joint_effort'
  - '/execute_trajectory/_action/cancel_goal'
  - '/execute_trajectory/_action/get_result'
  - '/execute_trajectory/_action/send_goal'
  - '/move_action/_action/cancel_goal'
  - '/move_action/_action/get_result'
  - '/move_action/_action/send_goal'
  - '/pm_robot_gonio_left_controller/follow_joint_trajectory/_action/cancel_goal'
  - '/pm_robot_gonio_left_controller/follow_joint_trajectory/_action/get_result'
  - '/pm_robot_gonio_left_controller/follow_joint_trajectory/_action/send_goal'
  - '/pm_robot_gonio_left_controller/query_state'
  - '/pm_robot_gonio_right_controller/follow_joint_trajectory/_action/cancel_goal'
  - '/pm_robot_gonio_right_controller/follow_joint_trajectory/_action/get_result'
  - '/pm_robot_gonio_right_controller/follow_joint_trajectory/_action/send_goal'
  - '/pm_robot_gonio_right_controller/query_state'
  - '/pm_robot_parallel_gripper_GAC/gripper_cmd/_action/cancel_goal'
  - '/pm_robot_parallel_gripper_GAC/gripper_cmd/_action/get_result'
  - '/pm_robot_parallel_gripper_GAC/gripper_cmd/_action/send_goal'
  - '/pm_robot_t_axis_controller/follow_joint_trajectory/_action/send_goal'
  - '/pm_robot_t_axis_controller/follow_joint_trajectory/_action/get_result'
  - '/pm_robot_t_axis_controller/follow_joint_trajectory/_action/cancel_goal'
  - '/pm_robot_t_axis_controller/query_state'
  - '/pm_robot_xyz_axis_controller/follow_joint_trajectory/_action/cancel_goal'
  - '/pm_robot_xyz_axis_controller/follow_joint_trajectory/_action/get_result'
  - '/pm_robot_xyz_axis_controller/follow_joint_trajectory/_action/send_goal'
  - '/pm_robot_xyz_axis_controller/query_state'
  - '/controller_manager/list_controller_types'
  - '/controller_manager/list_controllers'
  - '/controller_manager/load_controller'
  - '/controller_manager/reload_controller_libraries'
  - '/controller_manager/unload_controller'
  - '/controller_manager/switch_controller'
  - '/controller_manager/set_hardware_component_state'
  - '/controller_manager/list_hardware_components'
  - '/controller_manager/configure_controller'
  - '/controller_manager/list_hardware_interfaces'





    

# Be careful with this. All service clients with this service type will be hidden in the blacklist
clients_by_type:
  - 'rcl_interfaces/srv/GetParameters'
  - 'rcl_interfaces/srv/SetParameters'
  - 'rcl_interfaces/srv/ListParameters'
  - 'rcl_interfaces/srv/SetParametersAtomically'
  - 'rcl_interfaces/srv/GetParameterTypes'
  - 'rcl_interfaces/srv/DescribeParameters'
