# show only service clients with the following names
clients_by_name:
 - '/pm_moveit_server/move'
 - '/assembly_manager/'
 - '/pm_vision_manager/'

clients_by_type:
  # - 'rcl_interfaces/srv/GetParameters'

